### ISSUE TITLE
When a License is Insufficient, show error message instead of an exception

### ISSUE THREAD

**Issue by MikeAlhayek** [surevelox/OrchardCore.Modules#32]
If the user has an Insufficient License and navigated to "Multi Tenancy" >> "Settings" >> "Registration Pages" the page throws ex exception. 

![image](https://user-images.githubusercontent.com/24724371/176534451-af48d421-75b9-48d9-8751-792a35ae25fe.png)

Here you may consider displaying an error instead of throwing an exception.

**Comment by ns8482e** [comment]
@CrestApps thanks for reporting a bug.  

The current evaluation license is valid for 1.3 and 1.4. and It should not throw an exception 

However it seems C# Version class is considering 1.4 is less than 1.4.0.0 

Note from Microsoft docs.
>For two versions to be equal, the major, minor, build, and revision numbers of the first [Version](https://docs.microsoft.com/en-us/dotnet/api/system.version?view=net-6.0) object must be identical to those of the second [Version](https://docs.microsoft.com/en-us/dotnet/api/system.version?view=net-6.0) object. If the build or revision number of a [Version](https://docs.microsoft.com/en-us/dotnet/api/system.version?view=net-6.0) object is undefined, that [Version](https://docs.microsoft.com/en-us/dotnet/api/system.version?view=net-6.0) object is considered to be earlier than a [Version](https://docs.microsoft.com/en-us/dotnet/api/system.version?view=net-6.0) object whose build or revision number is equal to zero.

**Comment by ns8482e** [comment]
Fixed in 1.6.0-rc-20230603.1
