### ISSUE TITLE
Unable to go back in the sign up page

### ISSUE THREAD

**Issue by MikeAlhayek** [surevelox/OrchardCore.Modules#39]
**Describe the bug**
When a user go to `/tenants/signup` fills out the first step, on the verification step you can't click on "Previous" step. If you do, you'll get "Invalid code" error
![image](https://user-images.githubusercontent.com/24724371/179861915-8306145c-4d05-48f5-a65c-8604b31bfec3.png)

Also, there is no way to request a new pin. Add a button to allow the user to request a new pin.

**Comment by ns8482e** [comment]
Current page has to be valid To move away from current page

**Comment by ns8482e** [comment]
Are you getting `Invalid code` after providing valid code? You need to configure Email settings - Requires `OrchardCore.Email`. Enable it if you have not already and provid SMTP settings. for development you can provide `SpecifiedPickupDirectory` for offline emails

**Comment by ns8482e** [comment]
@CrestApps let me know if this is still the issue with latest preview or it can be closed

**Comment by MikeAlhayek** [comment]
@ns8482e, lets say a user provided invalid email in the account step, and during validation the user did not get an email. This brings up 3 issues.
1. The user does not know what email he/she provided in the previous step.
2. If they provided an invalid email, the user should be able to go to previous page to fix email address.
3. There is no way for the user to request another code to be-resent.

Solution for 1 is to show the email that is being verified on this screen. You may want to change the message to something like. "please check the email `provided@email.com`. We sent you a 6 digit verification code. Please enter the code below"

Solution for 2) allow the user to go to previous page even of the current page fail validation. Going back should not matter.

Solutions for 3) add a way to resend the verification code.

**Comment by ns8482e** [comment]
Fix is available in RC
