### ISSUE TITLE
Fix button spacing in the sign up page

### ISSUE THREAD

**Issue by MikeAlhayek** [surevelox/OrchardCore.Modules#40]
**Describe the bug**

![image](https://user-images.githubusercontent.com/24724371/179862543-079ddd3f-f891-467c-9ab9-c05955b1db44.png)

![image](https://user-images.githubusercontent.com/24724371/179862590-6a37b3c4-0f7a-4702-9cb9-1f7a76869913.png)

**Comment by ns8482e** [comment]
I guess it's issue with current theme

**Comment by ns8482e** [comment]
Fixed in latest preview

**Comment by ns8482e** [comment]
Fixed in 1.6.0-rc-20230603.1
