### ISSUE TITLE
The confiration email is missing link during signup

### ISSUE THREAD

**Issue by MikeAlhayek** [surevelox/OrchardCore.Modules#41]
**Describe the bug**
When a tenant signs up, the email look as follow

```
<p>Hi there,</p>
<p>Thank you for signing up for our services.</p>
<p>To get you started, please enter following code in verify screen.</p><br /><br />

<h3>137536 </h3><br/><br/>

<p>Alternatively you can <a href="">click here</a> to verify your account.</p> 

<p>Thank you</p>
```

the link is missing. Also, this email should probably be a template when one can change. Maybe also make the finish email as a template so one can change the body of the email

**Comment by ns8482e** [comment]
@CrestApps Email is a template that you can override

**Comment by ns8482e** [comment]
Link is fixed in latest RC
