### ISSUE TITLE
Exception is thrown when Stripe is not configured

### ISSUE THREAD

**Issue by MikeAlhayek** [surevelox/OrchardCore.Modules#48]
**Describe the bug**
When using the Payment Widget, while Stripe is not configured, an exception is thrown.

> StripeException: No API key provided. Set your API key using `StripeConfiguration.ApiKey = "<API-KEY>"`. You can generate API keys from the Stripe Dashboard. See https://stripe.com/docs/api/authentication for details or contact support at https://support.stripe.com/email if you have any questions.

**To Reproduce**
1. Add Payment step with Payment widget.
2. Sign up a client.

**Expected behavior**
A friendly error in alert should show up instead of exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/24724371/186264385-f2caf198-fe16-4dfe-9ef2-f78de825431f.png)

**Comment by ns8482e** [comment]
Fix will be available in next rc version

**Comment by ns8482e** [comment]
Fixed in 1.6.0-rc-20230603.1
