### ISSUE TITLE
It is not possible to publish a new menu item - the Publish and Cancel buttons are missing

### ISSUE THREAD

**Issue by patrikvolka** [surevelox/OrchardCore.Modules#50]
It is not possible to publish a new Menu item if Surevelox.OrchardCore.DevicePreview is enabled.
Video here: [https://youtu.be/8W43ugWVV7Y](https://youtu.be/8W43ugWVV7Y)

Used versions:
OrchardCore - 1.4.0
Surevelox.OrchardCore.DevicePreview - 1.3.0-rc-20221015.6
Surevelox.OrchardCore.Licensing - 1.3.0-rc-20221015.6

**Comment by ns8482e** [comment]
@patrikvolka  thank you for reporting the issue. The fix will be available in next rc version

**Comment by ns8482e** [comment]
@patrikvolka fix is available in 1.3.0-rc-20221117.8

**Comment by patrikvolka** [comment]
I confirm the removal of the problem. Great job
