### ISSUE TITLE
Defining ContentType for display in DevicePreview

### ISSUE THREAD

**Issue by patrikvolka** [surevelox/OrchardCore.Modules#56]
Hello,
is there a way to define which content types DevicePreview is used for and which not?

Example, I have two content types:
ContentType "A" - I want to use DevicePreview
ContentType "B" - I don't want to use DevicePreview

Thank you for your help.

**Comment by ns8482e** [comment]
There is in-built support - the module depends on orchard core's OOTB `ContentPreview` preview action shape. 

DevicePreview is rendered if there is Preview button shape available.
You can hide preview shape using placement and that won't show DevicePreview for that content type as below

```json
{
  "ContentPreview_Button": [
    {
      "place": "-",
      "contentType": [ "ContentTypeB" ]
    }
  ]
}
```

**Comment by patrikvolka** [comment]
Thanks
