### ISSUE TITLE
Please don't change my menu - or make it configuration so I can opt out of the change

### ISSUE THREAD

**Issue by MikeAlhayek** [surevelox/OrchardCore.Modules#57]
When enabling one of the modules, the standard menu changes to "Multi Tenancy"... It confused the crap out of me because I am used to OC's menu :)

Is there a way to either change it back to OC's menu or give me an option to opt out of that change? I think this change should be done in OC not this module. If module want to change the default menu, who wins? Not a good idea to change it.

**Comment by ns8482e** [comment]
Ok, will revert back to OC provided

**Comment by ns8482e** [comment]
Fixed in 1.6.0-rc-20230603.1
