### ISSUE TITLE
Do not throw an exception when the license is expired.

### ISSUE THREAD

**Issue by MikeAlhayek** [surevelox/OrchardCore.Modules#58]
When the license is expired, the signup process throws an exception. This is not a good thing to do. Instead, you may want to show a friendly message on the UI like "Sign up process is temporary unavailable. Please contact the site admin to resolve this issue."

In the admin, you can show more details like "Expired License: This feature requires a active license and your license is expired".

![image](https://user-images.githubusercontent.com/24724371/218849331-c1b7a272-2449-4665-84d0-28b3072e57fc.png)

**Comment by ns8482e** [comment]
Fixed in 1.6.0-rc-20230603.1
