### ISSUE TITLE
User Menu is not working after TwoFactorAuth enabled

### ISSUE THREAD

**Issue by rafalzmuda** [surevelox/OrchardCore.Modules#60]
Hi,
I'm using Orchard 1.6
When I enable Two Factor Auth Module then User Menu dropdown stops working with javascript error:
`Uncaught TypeError: $(...).tooltip is not a function`

I guess the user menu is overriden by module but it uses bootstrap4 and currently TheAdmin works with bootstrap5

Could You update markup to bs5?

**Comment by ns8482e** [comment]
Good catch- thank you for reporting, fix will be available in next release

**Comment by ns8482e** [comment]
Fixed in 1.6.0-rc-20230603.1
