### ISSUE TITLE
Empty modules ?

### ISSUE THREAD

**Issue by giannik** [surevelox/OrchardCore.Modules#8]
Why do I see no source code in these modules ?

**Comment by giannik** [comment]
Ok.
How does one purchase these modules ?

**Comment by ns8482e** [comment]
Support for Binary's can be provided using EULA

**Comment by giannik** [comment]
Can you give details on how to use and licence these premium modules ?
Also details on how to further customize these modules and support plans  ?

**Comment by ns8482e** [comment]
> Can you give details on how to use and licence these premium modules ?

Published modules are currently available on nuget.org - you can start using them right away.  Planned modules are currently in development and not available publicly on `nuget` yet.  

> Also details on how to further customize these modules and support plans ?

Issues/feature requests are tracked on this repository and support is provided based on priority of the issue and subscription level. Modules are being built considering extensibility - Feel free to add feature request, or for extensibility that you are specifically  looking for a module and will be added to to backlog for development 

IM gitter: @ns8482e  for modules and licensing details
